### ISSUE TITLE
1.9.2 login error

### ISSUE THREAD

**Issue by drtsou** [entersoftsa/eswebapiserver#1]
login error in test page.
message:invalid method name GetUserInfoImpl

i restored 1.9.0 and works
with the same config.json 

![eswebapi_192_login_error](https://cloud.githubusercontent.com/assets/3533881/16874936/0baf5b9e-4aa5-11e6-8a47-fb98c97de6dc.jpg)

**Comment by smene** [comment]
You should install in the application server of the EBS you are trying to connect to the latest versions of 

ESWebApiDefinitions.dll and  ESWebApiServices.dll
Please ask partner support to send you these files 

Thanks for using ENTERSOFT WEB API
