### ISSUE TITLE
pq params of type 'date range'

### ISSUE THREAD

**Issue by drtsou** [entersoftsa/eswebapiserver#3]
Hello,
i have to pass parameters to pq of type date range, that means 2 dates. what is the appropriate format for this? e.g. params["ADRegistrationDate"]="2017-01-01, 2017-02-29" is ok?
thanks

**Comment by entersoftsa** [comment]
New version of WEB API client in JavaScript / Angular 1.17.4.
This version has incorporated high level calls to initialize a ESDateParamVal object as well as documentation examples http://developer.entersoft.gr/eswebapi/#/api/es.Services.Web.esGlobals
